CREATE TABLE job (
  job_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  job_name               VARCHAR(100) NOT NULL,
  job_type               VARCHAR(25) NOT NULL,
  job_status             VARCHAR(25) NOT NULL,
  active_ind             BOOLEAN DEFAULT 1 NOT NULL,
  create_dt_tm           DATETIME NOT NULL,
  create_id              BIGINT NOT NULL,
  updt_dt_tm             DATETIME NOT NULL,
  updt_id                BIGINT NOT NULL,
  updt_cnt               INT DEFAULT 0 NOT NULL
);

CREATE TABLE job_detail (
  job_detail_id          BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  job_id                 BIGINT NOT NULL,
  job_status             VARCHAR(25) NOT NULL,
  parent_entity_id       BIGINT NULL,
  parent_entity_name     VARCHAR(25) NULL,
  active_ind             BOOLEAN DEFAULT 1 NOT NULL,
  create_dt_tm           DATETIME NOT NULL,
  create_id              BIGINT NOT NULL,
  updt_dt_tm             DATETIME NOT NULL,
  updt_id                BIGINT NOT NULL,
  updt_cnt               INT DEFAULT 0 NOT NULL
);
